name: mineral_bot
description: Build a powerful Discord applications in Dart
version: 1.0.0

publish_to: none

environment:
  sdk: '^3.2.0'

dependencies:
 mineral: ^4.0.0-dev.4
 mineral_cache: ^1.0.0-dev.2
 mysql_client: ^0.0.27
 os: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0